### ISSUE TITLE
Notice:  Array to string conversion

### ISSUE THREAD

**Issue by elazar** [WyriHaximus/PhergieUrl#10]
Something odd appears to be happening in [this block](https://github.com/WyriHaximus/PhergieUrl/blob/a9124f42fd23b862d0a9a6030cd8497ae176be0b/src/DefaultUrlHandler.php#L70-74). This notice showed up recently in my logs. I'm running v1.0.1.

```
[07-May-2015 10:30:14 America/Chicago] PHP Notice:  Array to string conversion in vendor/wyrihaximus/phergie-url/src/DefaultUrlHandler.php on line 74
```

**Comment by WyriHaximus** [comment]
Is this an random thing or a reproducible thing?

**Comment by elazar** [comment]
Seems random. It doesn't happen with all URLs, I can say that much for sure. I'll keep an eye out for more occurrences.

**Comment by WyriHaximus** [comment]
If you can provide more information it that would be really great :+1: . Right now it's like shooting in the dark for me.

**Comment by elazar** [comment]
Doesn't make much sense. `str_replace()` can take strings or arrays for any of its first three arguments. I'll go ahead and close this for now and re-open it if I find a case there can reproduce it reliably.

**Comment by WyriHaximus** [comment]
Alright, let me know if you find anything :+1:
