### ISSUE TITLE
Mime\Image not included by default

### ISSUE THREAD

**Issue by elazar** [WyriHaximus/PhergieUrl#11]
Per [this block](https://github.com/WyriHaximus/PhergieUrl/blob/a9124f42fd23b862d0a9a6030cd8497ae176be0b/src/DefaultUrlHandler.php#L52-54), `Mime\Image` is not included by default in the `DefaultUrlHandler`; I'm curious as to why this is. If it's due to that MIME handler's dependence on the GD extension, that makes sense, though a [`suggest` directive](https://getcomposer.org/doc/04-schema.md#suggest) should probably be included in `composer.json` for `ext-gd` and the `README.md` file should be supplemented to detail the MIME handlers, URL handlers, how to change them through configuration and/or implementing interfaces, etc.

**Comment by WyriHaximus** [comment]
Included it by default now :+1:

**Comment by WyriHaximus** [comment]
Also going to require ext-gd so everyone will have it. Tbh it would be rare to find a host without gd or people unable to install it.

**Comment by WyriHaximus** [comment]
It will mean tagging a new major release ;).
