### ISSUE TITLE
Mime\Image not working?

### ISSUE THREAD

**Issue by elazar** [WyriHaximus/PhergieUrl#12]
Not sure why, but the MIME Image handler doesn't appear to be returning the content type:

```
elazar: https://pbs.twimg.com/media/CEH6guMVIAA2Dur.png
Phergie: [http://gsc.io/u/29]
```

Here's the `curl` output for that URL, complete with a `Content-Type` response header that the MIME Image handler [should match against](https://github.com/WyriHaximus/PhergieUrl/blob/a9124f42fd23b862d0a9a6030cd8497ae176be0b/src/Mime/Image.php#L29):

```
$ curl -v https://pbs.twimg.com/media/CEH6guMVIAA2Dur.png
* Connected to pbs.twimg.com (199.96.57.7) port 443 (#0)
...
> GET /media/CEH6guMVIAA2Dur.png HTTP/1.1
> User-Agent: curl/7.35.0
> Host: pbs.twimg.com
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Wed, 13 May 2015 22:05:13 GMT
* Server tsa_b is not blacklisted
< Server: tsa_b
< cache-control: max-age=604800, must-revalidate
< content-md5: RBvsENn5ckf5ZD7KrBG5dQ==
< last-modified: Mon, 04 May 2015 01:07:54 GMT
< x-connection-hash: 8dbfb01091c33593e8b07f4f99bc77a4
< x-response-time: 32
< Content-Type: image/png
< Content-Length: 573668
< Accept-Ranges: bytes
< Via: 1.1 varnish
< Age: 2831
< X-Served-By: cache-tw-nyc1-cr1-20-TWNYC1
< X-Cache: HIT
< X-Cache-Hits: 3
< Expires: Thu, 28 May 2015 22:05:13 GMT
< X-Content-Type-Options: nosniff
```

Plugin configuration:

```php
use WyriHaximus\Phergie\Plugin\Url\Plugin as UrlPlugin;
use WyriHaximus\Phergie\Plugin\Url\Mime as MimeHandlers;
use WyriHaximus\Phergie\Plugin\Url\DefaultUrlHandler;
return [
    'plugins' => [
        new UrlPlugin([
            'handler' => new DefaultUrlHandler(
                '[%url-short%] %composed-title%',
                [
                        new MimeHandlers\Html,
                        new MimeHandlers\Image,
                ]
            ),
        ]),
    ],
];
```

**Comment by elazar** [comment]
It seems the format string fed to the `DefaultUrlHandler` constructor needs to include `%image-mime%`. It should would be nice if there was some way to make displaying only the page title for HTML documents and only the MIME type for images easy and/or the default behavior.

**Comment by WyriHaximus** [comment]
@elazar Could go for a very basic templating thing ala Twig in there allowing for if, elseif, else, endif

**Comment by elazar** [comment]
@WyriHaximus How about something like this? `%composed-title-or-image-mime%`. Check for `-or-` in the key, split they key on that and replace the placeholder with first constituent key with a non-empty value going from left to right.

**Comment by WyriHaximus** [comment]
@elazar hmm or I could put `image-mine` into `composed-title` since that was what it was intended for anyway.. :blush:

**Comment by elazar** [comment]
... or that. Yeah, do that. :p

**Comment by WyriHaximus** [comment]
There you go :+1:
