### ISSUE TITLE
Some entities aren't decoded in titles from HTML responses

### ISSUE THREAD

**Issue by elazar** [WyriHaximus/PhergieUrl#16]
```
elazar 10:22 Speaking of, if anyone wants to take on some low-hanging fruit: https://github.com/phergie/phergie-irc-plugin-react-twitter/issues/7
Phergie 10:22 [http://gsc.io/u/35] Entities aren&#39;t decoded · Issue #7 · phergie/phergie-irc-plugin-react-twitter · GitHub
```

Seems like [they should be](https://github.com/WyriHaximus/PhergieUrl/blob/692ae8a424ddb2fee163d47f21c00bd8700ad770/src/Mime/Html.php#L47), but as the output above indicates, they aren't. :(

Related: phergie/phergie-irc-plugin-react-twitter#7

**Comment by svpernova09** [comment]
This issue has been moved to the new repo: https://github.com/phergie/phergie-irc-plugin-react-url/issues
