### ISSUE TITLE
Parser handles XXX scene dirnames as URLs

### ISSUE THREAD

**Issue by hashworks** [WyriHaximus/PhergieUrl#6]
```
18:22:35 <%someone> GirlsDoPorn.E157.21.Years.Old.XXX.720p.WMV-KTR
18:22:35 <+Phergie> [ http://GirlsDoPorn.E157.21.Years.Old.XXX/ ]  
```

Yes, I'm in weird channels. My guess is that Twitter_Extractor looks for the .xxx TLD, not sure how to change this without altering Twitter_Extractor.

**Comment by WyriHaximus** [comment]
Hey no judgement from my part. Something that might be an extra check is to try and look it up using DNS to ensure it's a valid hostname.

**Comment by hashworks** [comment]
Yeah, something like that was in mind as well, otherwise it's kind of impossible to look for domains without protocol or www. prefix.

**Comment by WyriHaximus** [comment]
Alright I'll make it happen :+1:

**Comment by hashworks** [comment]
Altrough that won't fix the problem I guess - old.xxx is a registered domain.

**Comment by svpernova09** [comment]
This issue has been moved to the new repo: https://github.com/phergie/phergie-irc-plugin-react-url/issues
